### ISSUE TITLE
Doesn't run on release mode

### ISSUE THREAD

**Issue by Dev7Lw** [flutter-devs/image_gallery#13]
Steps to reproduce:
- flutter create bug
image_gallery: ^1.2.0 in pubspec.yaml
- flutter run --release 

ERROR: 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_gallery:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Dev\.gradle\caches\transforms-2\files-2.1\d8e69336e21c6a428e8a9e9d99518477\appcompat-1.0.0\res\values-v28\values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     C:\Users\Dev\.gradle\caches\transforms-2\files-2.1\d8e69336e21c6a428e8a9e9d99518477\appcompat-1.0.0\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     C:\Users\Dev\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\Dev\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      22,7s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    3,0s

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'camera'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin camera could not be built due to the issue above.

**Comment by Dev7Lw** [comment]
Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [versÃ£o 10.0.18363.1139], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

• No issues found!

**Comment by oGranny** [comment]
hi @Dev7Lw ,
how did you fix this? I am also getting the same issue but cannot find any way to solve it

**Comment by Dev7Lw** [comment]
@oGranny Hi!

As far as I remember, i tried several solutions but nothing work. 
Then, i used another package and worked for me. 
As far as  i remember, that was it.

**Comment by oGranny** [comment]
@Dev7Lw thanks for replying,
Can you tell the package name?
And what I found is it throws this error while building but it actually builds the apk 
I got to know this when I checked build folder
It is working normally but still to be in safe side I wanted to know the solution, 
Thanks

**Comment by Dev7Lw** [comment]
@oGranny 
I used  photo_manager to get all images of device
Separate then in folders and finally load all images of selected album.

I kinda make a camera UI like Instagram, to do so i used: 
```yaml
path_provider: ^1.6.18
  photo_manager: ^0.5.8
  provider: ^4.3.2+2
  path: ^1.7.0
  camera: ^0.5.8+9
```

Hope this helps.
